import React from 'react';
import {
  Container, Row, Col, Button, Nav, Link,
} from 'react-bootstrap';

const App = () => {
  const handleClick = () => {
    window.alert('you tapped to Button');
    console.log('you tapped to Button');
  };
  return (
    <Container fluid className="d-flex justify-content-between flex-column h-100 px-0 py-0">
      <Nav className="shadow-sm navbar navbar-light bg-white">
        <Container className="px-5">
          <a className="navbar-brand" to="/">Squaresseller</a>
          <Row className="d-flex justify-content-between">
            <Col className="d-flex">
              <Button variant="primary" onClick={handleClick}>
                Выход
              </Button>
            </Col>
          </Row>
        </Container>
      </Nav>
      <Container className="d-flex justify-content-top flex-column px-3">
        <Row className="h-100 py-4 px-3 main-box justify-content-center align-content-start">
          <Col className="col-1 square sc-1 " />
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " /> 
          <Col className="col-1 square sc-18 " /> 
          <Col className="col-1 square sc-19 " /> 
          <Col className="col-1 square sc-5 " /> 
          <Col className="col-1 square sc-6 " /> 
          <Col className="col-1 square sc-7 " /> 
          <Col className="col-1 square sc-1 " /> 
          <Col className="col-1 square sc-2 " /> 
          <Col className="col-1 square sc-12 " /> 
          <Col className="col-1 square sc-13 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-14 " /> 
          <Col className="col-1 square sc-15 " /> 
          <Col className="col-1 square sc-16 " />
          <Col className="col-1 square sc-18 " />
        </Row>
      </Container>
      <Nav className="shadow-lg navbar navbar-light bg-white">
        <Container className="justify-content-center">
          <a className="navbar-brand" to="/"> © Shadrin Ivan</a>
        </Container>
      </Nav>
    </Container>
  );
};

export default App;
